In [ ]:
Given a string s, find the longest palindromic substring in s. You may assume that the maximum length of s is 1000.

Example 1:

Input: "babad"
Output: "bab"
Note: "aba" is also a valid answer.
Example 2:

Input: "cbbd"
Output: "bb"

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/longest-palindromic-substring
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

In [4]:
#暴力法
class Solution:
    def longestPalindrome(self, s: str) -> str:
        if not s:
            return ''
        def checkPalindrome(subs):
            for i in range(len(subs)//2):
                if subs[i]!=subs[-i-1]:
                    return False
            return True
        longestPS=''
        maxLenP=0
        for i in range(len(s)):
            for j in range(i,len(s)):
                sub=s[i:j+1]
                if checkPalindrome(sub):
                    if len(sub)>maxLenP:
                        longestPS=sub
                        maxLenP=len(sub)
        return longestPS

s="babad"
Solution().longestPalindrome(s)

'bab'

In [ ]:
#最长公共字串
#利用广义后缀自动机求解最长公共字串

class Solution:
    def longestPalindrome(self, s: str) -> str:
        if not s:
            return ''
        reverse_s=s[::-1]
        ····放弃


In [13]:
#动态规划 python 超时了 emmm
import numpy as np
class Solution:
    def longestPalindrome(self, s: str) -> str:
        if not s:
            return ''
        n=len(s)
        if n==1:
            return s[0]

        dp=np.zeros((n,n))
        lens=1
        index=0
        for i in range(n):
            dp[i,i]=1
            if i<n-1 and s[i]==s[i+1]:
                dp[i][i+1]=2
                if lens<2:
                    index=i
                    lens=2
        
        for l in range(3,n+1):
            for i in range(n-l+1):
                if dp[i+1,i+l-2] and s[i]==s[i+l-1]:
                    dp[i,i+l-1]=dp[i+1,i+l-2]+1
                    if lens<l:
                        index=i
                        lens=l
        print(n,index,lens)
        for row in dp:
            print(row)
        return s[index:index+lens]
s="babadab"

Solution().longestPalindrome(s)

7 2 5
[1. 0. 2. 0. 0. 0. 0.]
[0. 1. 0. 2. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 3.]
[0. 0. 0. 1. 0. 2. 0.]
[0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 1.]


'badab'

In [ ]:
#人家写的这一版可以通过 ，事实上用numpy造成了更慢
class Solution:
    def longestPalindrome(self, s: str) -> str:
        size = len(s)
        if size < 2:
            return s

        dp = [[False for _ in range(size)] for _ in range(size)]

        max_len = 1
        start = 0

        for i in range(size):
            dp[i][i] = True

        for j in range(1, size):
            # 只有下面这一行代码不一样
            for i in range(j - 1, -1, -1):
                if s[i] == s[j]:
                    if j - i < 3:
                        dp[i][j] = True
                    else:
                        dp[i][j] = dp[i + 1][j - 1]
                else:
                    dp[i][j] = False

                if dp[i][j]:
                    cur_len = j - i + 1
                    if cur_len > max_len:
                        max_len = cur_len
                        start = i
        return s[start:start + max_len]

### DP c++版
```c++
class Solution {
public:
	const static int MAXN = 1000;
	int dp[MAXN][MAXN];
	string longestPalindrome(string s) {
		int n = s.size();
		if (n < 2) return s;
		int index = 0;
		int lens = 1;
		for (int i = 0; i < n; i++) dp[i][i] = 1;
		for (int l = 2; l <= n; l++) {
			for (int i = 0; i < n - l + 1; i++) {
				if (l == 2 && s[i] == s[i + l-1]) {
					dp[i][i + l - 1] = l;
					if (lens < l) {
						index = i;
						lens = l;
					}
				}
				else {
					if (dp[i + 1][i + l - 2] && s[i] == s[i + l - 1]) {
						dp[i][i + l - 1] = l;
						if (lens < l) {
							index = i;
							lens = l;
						}
					}
				}
			}
		}
		return s.substr(index, lens);
	}

};
```

In [22]:
# 中心扩展法
class Solution:
    def longestPalindrome(self, s: str) -> str:
        n=len(s)
        if n<2:
            return s
        start=0
        end=0
        for i in range(n):
            len1=self.expandAroundCenter(s,i,i)
            len2=self.expandAroundCenter(s,i,i+1)
            lenm=max(len1,len2)
            if lenm>end-start:
                start=i-((lenm-1)>>1)
                end=i+(lenm>>1)
        return s[start:end+1]
    
    def expandAroundCenter(self,s,le,ri):
        while le>=0 and ri<len(s) and s[le]==s[ri]:
            le-=1
            ri+=1
        return ri-le-1

s="babad"

Solution().longestPalindrome(s)

0 0 1 0 0
2 -1 3 1 0


''

```c++
#include<algorithm>
class Solution2 {
public:
	const static int MAXN = 1000;
	int dp[MAXN][MAXN];
	string longestPalindrome(string s) {
		int n = s.size();
		if (n < 2) return s;
		int index = 0;
		int lens = 1;
		for (int i = 0; i < n; i++) {
			int len1 = expandAroundCenter(s, i, i);
			int len2 = expandAroundCenter(s, i, i + 1);
			int len = max(len1, len2);
			if (len > lens) {
				index = i - ((len - 1) >> 1);
				lens = len;
			}
		}
		
		return s.substr(index, lens);
	}

	int expandAroundCenter(string s, int le, int ri) {
		while (le >= 0 && ri < s.size() && s[le] == s[ri]) {
			le--;
			ri++;
		}
		return ri - le - 1;
	}

};
```

In [25]:
#Manacher 算法
#https://leetcode-cn.com/problems/longest-palindromic-substring/solution/zhong-xin-kuo-san-dong-tai-gui-hua-by-liweiwei1419/

class Solution:
    def __expandAroundCenter(self,s,center):
        le=center-1
        ri=center+1
        r=0
        while le>=0 and ri<len(s) and s[le]==s[ri]:
            le-=1
            ri+=1
            r+=1
        return r

    def longestPalindrome(self, s: str) -> str:
        n=len(s)
        if n<2:
            return s
        t='#'
        for i in range(n):
            t+=s[i]
            t+='#'
        t_n=2*n+1

        max_len=1
        start=0

        for i in range(t_n):
            cur_len=self.__expandAroundCenter(t,i)
            if cur_len>max_len:
                max_len=cur_len
                start=(i-max_len)>>1
        return s[start:start+max_len]


s="babad"

Solution().longestPalindrome(s)

'bab'